# This is a basic workflow to help you get started with Actions

name: CI

# Run every hour or on demand
on:
  schedule:
    - cron: 0 * * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: oscarnevarezleal/ngrok-tunneling-action@dev
        id: tunnel
        with:
          port: 80
          ngrok_authtoken: ${{ secrets.NGROK_TOKEN }}
      - uses: ncipollo/release-action@v1
        id: xrelease
        with:
          name: endpoint
          tag: dev
          body: ${{ steps.tunnel.outputs.public-url }}
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo ${{ steps.tunnel.outputs.public-url }}
          sleep 30