# This is a basic workflow to help you get started with Actions

name: gh-backend-node

# Run every hour or on demand
on:
  #  schedule:
  #    - cron: '*/5 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  start:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Tunneling
        uses: oscarnevarezleal/ngrok-tunneling-action@dev
        id: tunnel
        with:
          port: 1313
          ngrok_authtoken: ${{ secrets.NGROK_TOKEN }}
          timeout: 5m

      - name : Preserve tunnel info
        run: |
          mv tunnels.json /tmp/tunnels.json

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'

      - uses: actions/checkout@v2

      - name: Get Hash
        id: hash
        run: echo "::set-output name=value::$(git rev-parse --short "$GITHUB_SHA")"

      - name: Run Hugo
        run : |
          ls -ltah
          mkdir -p /tmp/site
          git clone https://github.com/panr/hugo-theme-hello-friend.git /tmp/site/themes/hello-friend
          cp -a ./. /tmp/site/
          cd /tmp/site
          ls -ltah
          hugo server -b ${{ steps.tunnel.outputs.public-url }} --appendPort=false --liveReloadPort=443 --navigateToChanged -t hello-friend --port 1313 &

      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Preparation
        run: |
          # Encrypt the file
          gpg --local-user 4A8FB9698364B867 --sign /tmp/tunnels.json
          mv /tmp/tunnels.json.gpg .

      - uses: ncipollo/release-action@v1
        id: save-endpoint
        with:
          name: latest
          tag: latest
          artifacts: "tunnels.json.gpg"
          body: "-"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          echo "⚡ Listening"
          sleep 5m