# This is a basic workflow to help you get started with Actions

name: gh-backend-node

# Run every hour or on demand
on:
  schedule:
    - cron: * * * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: oscarnevarezleal/ngrok-tunneling-action@dev
        id: tunnel
        with:
          port: 80
          ngrok_authtoken: ${{ secrets.NGROK_TOKEN }}
          timeout: 5m
      - uses: stefanzweifel/git-auto-commit-action@v4
        id: auto-commit-action
        with:
          # Optional, but recommended
          # Defaults to "Apply automatic changes"
          commit_message: "gh-node-registered"

          # Optional. Used by `git-commit`.
          # See https://git-scm.com/docs/git-commit#_options
          commit_options: '--allow-empty'

          # Optional local file path to the repository
          # Defaults to the root of the repository
          repository: .

          # Optional. Used by `git-status`
          # See https://git-scm.com/docs/git-status#_options
          status_options: '--untracked-files=no'

          # Optional glob pattern of files which should be added to the commit
          file_pattern: '*.json'

          # Optional. Used by `git-push`
          # See https://git-scm.com/docs/git-push#_options
          push_options: '--force'

          # Optional. Disable dirty check and always try to create a commit and push
          skip_dirty_check: true

          # Optional. Skip internal call to `git fetch`
          skip_fetch: true

          # Optional. Prevents the shell from expanding filenames.
          # Details: https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html
          disable_globbing: true
      - run: |
          echo ${{ steps.auto-commit-action.outputs.commit_hash }}