name: gh-on-register

on:
  workflow_run:
    workflows: ["gh-backend-node"]
    types:
      - requested
  push:
    branches:
      - dev

jobs:
  # This workflow contains a single job called "build"
  reacting:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - id: wait
        name: wait
        run: sleep 60
      - id: node
        if: ${{ startsWith(github.event.head_commit.message, 'gh-node-registered') }}
        run: |
          echo "⚡ Reacting to gh-backend-node registration"
          url=$(cat tunnels.json | jq -rc '.tunnels[0].public_url')
          echo "✨ Next: screenshot $url"
          echo "::set-output name=url::${url}"
      - uses: actions/checkout@v2
      - name: screenshots-ci-action
        if: ${{ startsWith(github.event.head_commit.message, 'gh-node-registered') }}
        id: screenshot
        uses: flameddd/screenshots-ci-action@v1.1.1
        with:
          url: ${{ steps.node.outputs.url }}
          devices: iPhone 6,iPhone 6 landscape,Nexus 7,Pad Pro,Galaxy S III landscape,iPad Pro landscape