name: gh-on-register

on:
  workflow_run:
    workflows: ["gh-backend-node"]
    types:
      - requested
jobs:
  # This workflow contains a single job called "build"
  reacting:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      - uses: actions/checkout@v2
      - name : After checkout
        run: |
          ls -ltah
          gpg --output tunnels.json --decrypt tunnels.json.gpg
          cat tunnels.json
      - id: wait
        name: wait
        run: sleep 30
      - id: node
        if: ${{ startsWith(github.event.head_commit.message, 'gh-node-registered') }}
        run: |
          echo "⚡ Reacting to gh-backend-node registration"
          url=$(cat tunnels.json | jq -rc '.tunnels[0].public_url')
          echo "✨ Next: screenshot $url"
          echo "::set-output name=url::${url}"
      - uses: actions/checkout@v2
      - name: screenshots-ci-action
        if: ${{ startsWith(github.event.head_commit.message, 'gh-') }}
        id: screenshot
        uses: flameddd/screenshots-ci-action@v1.1.1
        with:
          url: ${{ steps.node.outputs.url }}
          devices: iPhone 6,iPhone 6 landscape,Nexus 7,Pad Pro,Galaxy S III landscape,iPad Pro landscape