# This is a basic workflow to help you get started with Actions

name: gh-on-register

# Run every hour or on demand
on:
  push:
    branches:
      - dev

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - id: node
        if: ${{ startsWith(github.event.head_commit.message, 'gh-node-registered') }}
        run: |
          echo "⚡ Reacting to node registration"
          url=$(cat tunnels.json | jq -rc '.tunnels[0].public_url')
          echo "✨ Next: screenshot $url"
          echo "::set-output name=url::${url}"
      - name: screenshots-ci-action
        if: ${{ startsWith(github.event.head_commit.message, 'gh-node-registered') }}
        id: screenshot
        uses: flameddd/screenshots-ci-action@v1.1.1
        with:
          url: ${{ steps.node.outputs.url }}
          devices: iPhone 6,iPhone 6 landscape,Nexus 7,Pad Pro,Galaxy S III landscape,iPad Pro landscape